### ISSUE TITLE
hello, about ipc=0.01 and ipc=1 batch workloads, there seems to be no code on github

### ISSUE THREAD

**Issue by wxggg** [yangxi/elfen#1]
hello yangxi, i am reproducing your work about elfen, but i can't find the code of producing the batch workloads of ipc=0.01 and ipc=1, you said in the paper that 

> The first uses a non-temporal store and memory fence to continuously block on memory, giving an IPC of 0.01. For instance, the Intel PAUSE instruction has a similar IPC. The other performs a tight loop doing nothing (IPC=1) when running alone. 

But i am wondering how you realize it, thanks for you reply!!!

**Comment by yangxi** [comment]
Thanks, I forgot to add them to the repository. I am refactoring the elfen code now, will try to add the batch micro-benchmarks ASAP. If you need them now, I can send a copy to your email.

**Comment by wxggg** [comment]
Thanks for your reply, if convenient, would you please send to my email wxg15527063842@gmail.com , thanks very much ! Otherwise i can still wait for you to refactor the code.
